---

platform: linux

image_resource:
  type: docker-image
  source: {repository: czero/rootfs}

params:
  OPSMAN_DOMAIN_OR_IP_ADDRESS:
  OPSMAN_CLIENT_ID:
  OPSMAN_CLIENT_SECRET:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  OM_DECRYPTION_PWD:

inputs:
  - name: pcf-pipelines

run:
  path: pcf-pipelines/tasks/config-opsman/task.sh
