---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang

inputs:
- name: pcf-pipelines

run:
  path: bash
  args:
  - -ce
  - |
    export GOPATH=$PWD/go
    export PATH=$GOPATH/bin:$PATH

    # install glide for dependency management
    curl -k https://glide.sh/get | sh

    pushd pcf-pipelines
      glide up
      ginkgo -p -r -randomizeAllSpecs
    popd
