# groups:
# - name: opsmngr-upgrade
#   jobs:

resources:
- name: concourse-tasks-bundle
  type: github-release
  source:
    user: c0-ops
    repository: concourse-tasks-bundle
    access_token: {{github_token}}

jobs:
- name: export-opsmgr
  plan:
  - get: concourse-tasks-bundle
  - task: export-opsmgr-task
    file: concourse-tasks-bundle/export-opsmgr-settings/task.yml
    params:
      OPSMAN_USERNAME: {{opsman_admin_username}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_URI: {{opsman_uri}}
      OPSMAN_SETTINGS_FILENAME: installation.zip

- name: stop-exiting-opsmgr-vm
  plan:
  - get: concourse-tasks-bundle
    passed: [export-opsmgr]
  - task: placeholder-for-stopping-current-opsmgr-vm
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: cloudfoundry/cflinuxfs2
      run:
        path: echo
        args:
        - "Placeholder for task that will 1) extract current OpsMgr VM info and 2) stop it"

- name: setup-updated-opsmgr-vm
  plan:
  - get: concourse-tasks-bundle
    passed: [stop-exiting-opsmgr-vm]
  - task: placeholder-for-updated-opsmgr-vm
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: cloudfoundry/cflinuxfs2
      run:
        path: echo
        args:
        - "Placeholder for task that will 1) download new OM VM file and 2) start VM up"

- name: import-opsmgr
  plan:
  - get: concourse-tasks-bundle
    passed: [setup-updated-opsmgr-vm]
  - task: import-opsmgr-task
    file: concourse-tasks-bundle/import-opsmgr-settings/task.yml
    params:
      OPSMAN_USERNAME: {{opsman_admin_username}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_URI: {{opsman_uri}}
      OPSMAN_SETTINGS_FILENAME: installation.zip
      OPSMAN_PASSPHRASE: {{opsman_passphrase}}

- name: trigger-installations
  plan:
  - get: concourse-tasks-bundle
    passed: [import-opsmgr]
  - task: apply-changes-task
    file: concourse-tasks-bundle/apply-changes/task.yml
    params:
      OPSMAN_USERNAME: {{opsman_admin_username}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_URI: {{opsman_uri}}
