---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/cflinuxfs2

inputs:
- name: pcf-pipelines

params:
  AZURE_SERVICE_PRINCIPAL_ID:
  AZURE_SERVICE_PRINCIPAL_PASSWORD:
  AZURE_TENANT_ID:
  RESOURCE_GROUP:
  PARENT_DNS_ZONE:
  CHILD_DNS_ZONE_NAME:

run:
  path: pcf-pipelines/ci/tasks/delegate-azure-dns-zone/task.sh
