pivnet_token: CHANGEME
opsman_admin_username: CHANGEME
opsman_admin_password: CHANGEME
opsman_uri: CHANGEME
github_token: yyyyyyyyyyyyyyyyy
iaas_type: gcp
poll_interval: 1h
opsman_timeout_seconds: 5m
