opsman_timeout: CHANGEME
opsman_admin_username: CHANGEME
opsman_admin_password: CHANGEME
opsman_uri: http://example.com
opsman_passphrase: CHANGEME
github_token: CHANGEME
pivnet_token: CHANGEME
vcenter_url: http://example.com
vcenter_username: CHANGEME
vcenter_password: CHANGEME
vcenter_datacenter: CHANGEME
vcenter_cluster: CHANGEME
vcenter_datastore: CHANGEME
vcenter_resource_pool: CHANGEME
opsman_vm_folder: CHANGEME
opsman_ip: CHANGEME
netmask: CHANGEME
gateway: CHANGEME
dns: CHANGEME
ntp: CHANGEME
opsman_network: CHANGEME
iaas_type: CHANGEME
