poll_interval: 1h

pivnet_token: x2gi1XD9FSm8gzdnSWRZ #CHANGEME
cf_api_uri: https://api.run.pivotal.io #CHANGEME
cf_user: bblincoe@pivotal.io #CHANGEME
cf_password: !BPb1024 #CHANGEME
cf_org: bblincoe-org #CHANGEME
cf_space: development #CHANGEME

git_private_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIJKQIBAAKCAgEApHncLWtKfHpL8E9IAx2fggC0zLpGmWXJXxBym9DIBQ5hUGbZ
  /R+BbJO1iWoXzOSL4pMoHgU8MvSEdXMccesCxae89tC31ovJ/uN1RgaEPtJdmCwO
  DMpfD5Bgk+Lt6Ee+2lx6kEwX/poqr5t2tLwx/0Bwbv1wgsSlpL21blpHm5x3KNKO
  n16is4kQF+ga+BNlDy2CcsgXkcifn/6wEgpZkTqHvZUbGE6VNEkxVFrVWE1Lr4le
  4C8mYx6F63+Puu8RfR0eNGBxfJxMoCBahYv7ePxpAC6QtGUR+u7OK2Y3UvIlKb+r
  GSv+GmWKZmeUvaDuH/j1FL6Gt3on+uLQUW3/wgkBNNUejRgxo2aUnJz0Tfr9bG+B
  h/ep0kn/jrzt0k/G5XxmZl63H9eHYGg6Sx5an4K8cybpJVyVXS8bGfz3T62FYq5u
  d5RDgq5PnQi7AQXUd8vJ2ndmTQr7u6Mzvv7Xc9axTKmmTtCv1fY6SSPrczX4ZVO5
  z36AWvs+v5BgW0BfaEOeFn8god9530T055yEF/TIM8bow5Zc/kQfxowk2zG5A5ez
  OzMx+n+/BYU0BnPMUalqupHBmrtcG5qGTuIdxa1upIbdUhio8mpFx9R2L26EqWju
  cDkoQBUjdPY23WFIlFlf+xCbPp9PcXrdnAAGnFBY0JlolSxawGBSbAcsIBECAwEA
  AQKCAgB3IunQYGn41mERNWw1DY0PjtFnhfpDfM4rNO+/W7C2sN7ebVGzHtIRwsB5
  Q8bvnBCTUwJ5FFOxmRolNPdCsPc2ErU2lqLDHkh3f2zgBzJdiuVOp4KZ0zCeRnce
  R/8KBIYDB3+j6+ppemQ3BUYrzjHs8VE/pAaOQkC1ntC/mVdLKT/K6xFx8QurPjnR
  B0gZr3rBTraxy6v+5jJxovsIZkTQhHP0Z//TUICU+ftoXc8xgfOzt65odt64Z1Cb
  7689uZOSa7gIOl+Z4mFCj4ziNS43SaYJArHAaYFnoPjnyMeEJm+y2Onnds09c5WX
  ban43Yv+zsc/em58klhJS2eXxDS/v0u0fDE8V3n4JVs6W5rd6+n3+Zs/cvn/WwOA
  E/udpCvi+gMb7A0BnABNnK2WBozFz0UNaAeYIAcCLoi2PKrm0wMO7qEQkZt2W5/2
  U1KXJSZuSwM6VPE6HtDZ+3+x9bWbGVu9xv6bbjUaWdQzVFVm0ClHjBGw0QxjNa/m
  EUcPT6VP7N5pjUoXahOxpGqTrzbGhVxqXW/XnE5h5SNbsSy7bUJxjVzy5hdAnXR0
  yOT9OhTp1cbMZZKO5o0WYo8KzS7uIaytKQostKIaFf1jTJThdWbjg75MexgIijgY
  GntE4ZPDsA9isEDAL39VNScYVXzF6xglYY2nVw1OwmshF486jQKCAQEA1wixKf5e
  zzSAQZ5fJRXjftybTSz9UDYDnrfVl4o7xYr4O0vLhNrMZ/m+fYrmLiCXWQykDT0e
  K8sl+lHUExfGRLXlL9HByVrExw3evIviNDbgVX1Dujp5Jd5Mc3sQEz+SSUgV9E+1
  gEsLkXUfGaPZinphOsy4HpCVAmWEGAYyFuMWRv1M3U8jTeW61rdY70YcndnqRZ0X
  TMOiNPx+Z9KputyP0HLqLaFa+ije3TPfrvseC1O+Obdc65giqt922sXjZYDo0Qsr
  0PWQK09wEovGsLUxAAD1xlnvv4PKX0pvCX95bNyH1UcjXCQRoZPUSkMMqT4njw7O
  /zat45r5ZSzGSwKCAQEAw89u9JUDH3qhBUQ+HGJ8wxu+MQ0hW/DBgrozS4R8ZwLW
  kUcYdr9UspdY0WGWzJZEj8RlGYE68m7A0j6qAFKRM9Ji7RU+JoVzTKI5wK3WSvtp
  oGiR7XzEdIvpX7J8CZAvxk+Y6t1jhxANEfYWJ3YeE1AzXPL/O5U3c56kJ08bmzGy
  jdp7iSHWYjEd0Cfd+RxHR57/ry0XIjG0RAt9ZeDuXLZadzmr0y30CfDYYj2xapyU
  WAdpFOZ6vm2G1oDCGbkpjcxhP4SaWYDWwZPx4KSGKbDbJ0WQAxNobC8BHQYByC76
  fiOrqeIeAugMHNjegIlnQvtQo3C577P5SyyBfHTpkwKCAQEAgCZ09tLai9/9A54v
  k7lsv8EXaLIEMRZPp/pk94/xOTQt5aCxJHcE1H5ZERaDQUA5El/fMOiYn37NHlY/
  7jT/+xjwAkSembJXjU1tza4L3BRMM4aYo1aPtoq5wyS3GtGLC9NDCjuqrk+LEF/d
  bflg/w8Z/OHeZJDDzQ7U30Bp/4vMTfhNI6MzJgxgAfB4tvhwu34QCPaq2RvKAovr
  hVJdxrgFmTOy7gi4YFeVIfz1NKIBcLyypFDrtpgPKQhOG+lNMMPXfCWNMlX2WmlY
  ICVe/xasohTwZApbQCZ5p7qDXAS1R7RR20AvCY2RWFrybGNzGzWoe7BWmnBqxzcn
  pC0/6wKCAQEAqemFSZ1IoXdC5JQMJYtc4d1gE6ZmLSbkdHDo8/3aCXVQBa6gzuJG
  N9bXDpHVTmCSzAJLDG+0XAy5K3ePA0qij0pf54TIcprYq0YWQVlXm6dASB6VinP6
  8Xs7Hnx937qLilUlx6AmrlvCS7S0ErgPbwjoGR8PVX+tJ5ogra+ar/fXDfrpudxv
  8LLYQPlnR7Q/MioJitPgwB5LY8RooxAlJrRiGhUkQdMdccbZrZ4FJxMKMrzzdVxu
  ZHIcUGRYigO/yDjypjCF02bWdBHSEPITLXg3I4PcbJ7ZvQ6os6uzvibt3KlNW9RH
  4JPFdv7FTNpujZQQrFK0NgmBKLdNAVdeGwKCAQBEUneT8FPRxqgLXfPIb630FpI8
  2VtXsjmbHde1CGjiIu8Yqzq7B+lX9B10p10O1SWxZuwLuKrwT4Ep1jchdgSvnpUb
  YOEH2sjilOhpEm1wBZg34oIzcUBhorCIdgUwi9pP9J8t0XwilnLZ/kAjlTutjxwW
  MX2QdN4+kHzLafTm7VWwlagtxU7CYzym9/UuyV6v+IAdWLsOOJULoKepGcbbA6R0
  rv91BACBVJEFk4YvmpACuHiF7BGxYf6g0NvOlLtgyEdyhRVotfFLUaVgjsWi/xdB
  C/G4L0/n/UcWoTKnb8haktafDrNCMIQLMrCtrMRgrdXuAbaoywCQP5q9B6k7
  -----END RSA PRIVATE KEY-----

#CHANGEME
